---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Administration:
    - Portainer:
        icon: portainer.png
        href: "https://portainer.nurul.online"
        description: Container Manager
        # server: my-docker # The docker server that was configured
        # container: portainer

- Monitoring:
    - Pi-Hole:
        icon: pi-hole.png
        href: "https://pihole.nurul.online/admin"
        description: Block Ads
        widget:
          type: pihole
          url: https://pihole.nurul.online
          key: e17e376d305cc71ab74e867d79ea1503a001d2985468a732941527c28d659226
